import {
    processProfiles,
    processSnpData,
    getRsIds,
    getChromosomeAndPosition,
    generateAlleleDosage,
    estimateWeibullParameters,
    getSnpsInfo,
    renderHistogram,
    displaySNP,
    createTable,
    renderSNPHistograms,
    sleep,
    countOccurrences,
    parseFile,
    parseCsv,
    empiricalCdf,
    generateWeibullIncidenceCurve,
    processPRS,
    matchCasesWithControls,
    dataToCSV,
    downloadCSV
} from './data-generator';

export {
    processProfiles,
    processSnpData,
    getRsIds,
    getChromosomeAndPosition,
    generateAlleleDosage,
    estimateWeibullParameters,
    getSnpsInfo,
    renderHistogram,
    displaySNP,
    createTable,
    renderSNPHistograms,
    sleep,
    countOccurrences,
    parseFile,
    parseCsv,
    empiricalCdf,
    generateWeibullIncidenceCurve,
    processPRS,
    matchCasesWithControls,
    dataToCSV,
    downloadCSV
};